export const paths = {
  // Public Website
  home: '/',
  services: '/services',
  pricing: '/pricing',
  about: '/about',
  faq: '/faq',
  contact: '/contact',
  privacy: '/privacy',
  terms: '/terms',

  // Authentication
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  totp: '/auth/totp',

  // Authenticated Application
  app: '/app',
  dashboard: '/app',
  workspaces: '/app/workspaces',
  projects: '/app/projects',
  tasks: '/app/tasks',
  documents: '/app/documents',
  sources: '/app/documents',
  research: '/app/research',
  ai: '/app/ai',
  assistant: '/app/ai',
  writing: '/app/research',
  analysis: '/app/analysis',
  reports: '/app/reports',
  references: '/app/references',
  billing: '/app/billing',
  notifications: '/app/notifications',
  profile: '/app/settings/profile',
  security: '/app/settings/security',
  settings: '/app/settings',

  // Administration
  admin: '/admin',
  adminPublicSite: '/admin/public-site',
  adminContactSubmissions: '/admin/contact-submissions',

  // Parametric routes
  project: (projectId: string) => `/app/projects/${projectId}`,
  projectOverview: (projectId: string) => `/app/projects/${projectId}`,
  projectSources: (projectId: string) => `/app/projects/${projectId}/sources`,
  projectDocuments: (projectId: string) => `/app/projects/${projectId}/sources`,
  projectAssistant: (projectId: string) => `/app/projects/${projectId}/assistant`,
  projectAi: (projectId: string) => `/app/projects/${projectId}/assistant`,
  projectWriting: (projectId: string) => `/app/projects/${projectId}/writing`,
  projectAnalysis: (projectId: string) => `/app/projects/${projectId}/analysis`,
  projectReport: (projectId: string) => `/app/projects/${projectId}/report`,
  projectResearch: (projectId: string) => `/app/projects/${projectId}/research`,
  projectAdvanced: (projectId: string) => `/app/projects/${projectId}/research/advanced`,
  projectTasks: (projectId: string) => `/app/projects/${projectId}/tasks`,
  projectReferences: (projectId: string) => `/app/projects/${projectId}/references`,
  projectSettings: (projectId: string) => `/app/projects/${projectId}/settings`,
};
