package com.researchassistant.billing;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.researchassistant.IntegrationTestSupport;
import com.researchassistant.billing.dto.BillingDtos.InitializePaymentRequest;
import com.researchassistant.identity.entity.User;
import com.researchassistant.identity.entity.UserStatus;
import com.researchassistant.identity.repository.UserRepository;
import com.researchassistant.subscription.*;
import com.researchassistant.workspace.entity.*;
import com.researchassistant.workspace.repository.WorkspaceMembershipRepository;
import com.researchassistant.workspace.repository.WorkspaceRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.data.domain.Pageable;
import org.springframework.http.MediaType;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Integration tests for the subscription upgrade flow.
 *
 * <p>Authentication uses real HMAC-SHA256 JWTs generated by
 * {@link IntegrationTestSupport#bearerToken(UUID, String)} so that
 * the full Spring Security filter chain is exercised.</p>
 *
 * <p>External Paystack calls are replaced with a {@link MockitoBean}
 * so the tests do not require network access.</p>
 */
@SpringBootTest(properties = {
        "app.security.jwt.secret=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=",
        "app.security.credentials.encryption-key=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
})
@AutoConfigureMockMvc
@Transactional
class SubscriptionUpgradeIntegrationTests extends IntegrationTestSupport {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private WorkspaceRepository workspaceRepository;

    @Autowired
    private WorkspaceMembershipRepository membershipRepository;

    @Autowired
    private SubscriptionPlanRepository planRepository;

    @Autowired
    private WorkspaceSubscriptionRepository subscriptionRepository;

    @Autowired
    private BillingPaymentIntentRepository intentRepository;

    @Autowired
    private PaymentAttemptRepository attemptRepository;

    @Autowired
    private SubscriptionPlanPriceRepository planPriceRepository;

    @Autowired
    private MoneyMinorUnitConverter moneyMinorUnitConverter;

    @MockitoBean
    private PaymentProvider paymentProvider;

    private User user;
    private Workspace workspace;
    private SubscriptionPlan freePlan;
    private SubscriptionPlan studentPlan;
    private SubscriptionPlan proPlan;
    private String userToken;

    @BeforeEach
    void setUp() {
        // Setup provider mock defaults
        Mockito.when(paymentProvider.providerType()).thenReturn(PaymentProviderType.PAYSTACK);
        Mockito.when(paymentProvider.environment()).thenReturn(PaymentEnvironment.TEST);
        Mockito.when(paymentProvider.toSmallestUnit(any())).thenAnswer(inv -> {
            BigDecimal amt = inv.getArgument(0);
            return moneyMinorUnitConverter.toMinorUnits(amt, "GHS");
        });
        Mockito.when(paymentProvider.initialize(any(PaymentAttempt.class), any(SubscriptionPlan.class)))
                .thenAnswer(inv -> {
                    PaymentAttempt att = inv.getArgument(0);
                    return new PaystackInitializeResponse(
                            true,
                            "Authorization URL created",
                            new PaystackInitializeData(
                                    "https://checkout.paystack.com/test-" + att.getInternalReference(),
                                    "test-code",
                                    att.getInternalReference()
                            )
                    );
                });

        user = new User();
        user.setEmail("subscriber-" + UUID.randomUUID() + "@university.edu");
        user.setPasswordHash("hashedpassword");
        user.setFirstName("Ada");
        user.setLastName("Lovelace");
        user.setStatus(UserStatus.ACTIVE);
        user = userRepository.save(user);

        // Generate token now that the user has a persisted ID
        userToken = bearerToken(user.getId(), user.getEmail());

        workspace = new Workspace();
        workspace.setName("Ada's Lab");
        workspace.setOwner(user);
        workspace.setType(WorkspaceType.PERSONAL);
        workspace.setStatus(WorkspaceStatus.ACTIVE);
        workspace = workspaceRepository.save(workspace);

        WorkspaceMembership membership = new WorkspaceMembership();
        membership.setWorkspace(workspace);
        membership.setUser(user);
        membership.setRole(WorkspaceRole.OWNER);
        membership.setStatus(WorkspaceMembershipStatus.ACTIVE);
        membershipRepository.save(membership);

        freePlan = planRepository.findByCodeIgnoreCase("FREE")
                .orElseGet(() -> {
                    SubscriptionPlan fp = new SubscriptionPlan();
                    fp.setCode("FREE");
                    fp.setName("Free Plan");
                    fp.setDescription("Default free plan");
                    fp.setStatus(SubscriptionPlanStatus.ACTIVE);
                    fp.setBillingInterval(BillingInterval.NONE);
                    fp.setPrice(BigDecimal.ZERO);
                    fp.setCurrency("GHS");
                    fp.setPubliclyAvailable(true);
                    fp.setDisplayOrder(0);
                    return planRepository.save(fp);
                });

        studentPlan = planRepository.findByCodeIgnoreCase("STUDENT")
                .orElseGet(() -> {
                    SubscriptionPlan sp = new SubscriptionPlan();
                    sp.setCode("STUDENT");
                    sp.setName("Student Plan");
                    sp.setDescription("Student plan");
                    sp.setStatus(SubscriptionPlanStatus.ACTIVE);
                    sp.setBillingInterval(BillingInterval.MONTHLY);
                    sp.setPrice(BigDecimal.valueOf(20.00));
                    sp.setCurrency("GHS");
                    sp.setPubliclyAvailable(true);
                    sp.setDisplayOrder(1);
                    return planRepository.save(sp);
                });

        proPlan = planRepository.findByCodeIgnoreCase("PRO")
                .orElseGet(() -> {
                    SubscriptionPlan pp = new SubscriptionPlan();
                    pp.setCode("PRO");
                    pp.setName("Pro Plan");
                    pp.setDescription("Pro researcher plan");
                    pp.setStatus(SubscriptionPlanStatus.ACTIVE);
                    pp.setBillingInterval(BillingInterval.MONTHLY);
                    pp.setPrice(BigDecimal.valueOf(100.00));
                    pp.setCurrency("GHS");
                    pp.setPubliclyAvailable(true);
                    pp.setFeatured(true);
                    pp.setDisplayOrder(2);
                    return planRepository.save(pp);
                });

        // Place workspace on FREE plan
        WorkspaceSubscription initialSub = new WorkspaceSubscription();
        initialSub.setWorkspace(workspace);
        initialSub.setPlan(freePlan);
        initialSub.setStatus(WorkspaceSubscriptionStatus.ACTIVE);
        initialSub.setBillingInterval(BillingInterval.NONE);
        initialSub.setStartsAt(java.time.OffsetDateTime.now());
        initialSub.setCurrentPeriodStart(java.time.OffsetDateTime.now());
        initialSub.setCurrentPeriodEnd(java.time.OffsetDateTime.now().plusYears(10));
        subscriptionRepository.save(initialSub);
    }

    @Test
    void normalUserStartsOnFreePlan() throws Exception {
        mockMvc.perform(get("/api/v1/workspaces/{workspaceId}/billing/subscription", workspace.getId())
                        .header("Authorization", userToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.planCode", is("FREE")))
                .andExpect(jsonPath("$.status", is("ACTIVE")));
    }

    @Test
    void studentMonthlyCheckoutUsesAuthoritative26Ghs40And2640MinorUnits() throws Exception {
        InitializePaymentRequest request = new InitializePaymentRequest("STUDENT", BillingInterval.MONTHLY);

        mockMvc.perform(post("/api/v1/workspaces/{workspaceId}/billing/initialize", workspace.getId())
                        .header("Authorization", userToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.authorizationUrl", containsString("checkout.paystack.com")))
                .andExpect(jsonPath("$.reference", notNullValue()));

        BillingPaymentIntent intent = intentRepository
                .findAllByWorkspaceIdOrderByCreatedAtDesc(workspace.getId(), Pageable.unpaged())
                .getContent()
                .get(0);

        assertThat(intent.getPlan().getCode()).isEqualTo("STUDENT");
        // Base: 20.00 + Processing (2%): 0.40 + AI (30%): 6.00 = 26.40 GHS (2640 minor units)
        assertThat(intent.getExpectedAmount()).isEqualByComparingTo(new BigDecimal("26.40"));
        assertThat(intent.getBaseAmount()).isEqualByComparingTo(new BigDecimal("20.00"));
        assertThat(intent.getProcessingFeeAmount()).isEqualByComparingTo(new BigDecimal("0.40"));
        assertThat(intent.getAiGenerationFeeAmount()).isEqualByComparingTo(new BigDecimal("6.00"));
        assertThat(intent.getTotalAmount()).isEqualByComparingTo(new BigDecimal("26.40"));
        assertThat(moneyMinorUnitConverter.toMinorUnits(intent.getExpectedAmount(), intent.getCurrency())).isEqualTo(2640L);
    }

    @Test
    void proMonthlyCheckoutUsesAuthoritative132GhsAnd13200MinorUnits() throws Exception {
        InitializePaymentRequest request = new InitializePaymentRequest("PRO", BillingInterval.MONTHLY);

        mockMvc.perform(post("/api/v1/workspaces/{workspaceId}/billing/initialize", workspace.getId())
                        .header("Authorization", userToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.authorizationUrl", containsString("checkout.paystack.com")))
                .andExpect(jsonPath("$.reference", notNullValue()));

        BillingPaymentIntent intent = intentRepository
                .findAllByWorkspaceIdOrderByCreatedAtDesc(workspace.getId(), Pageable.unpaged())
                .getContent()
                .get(0);

        assertThat(intent.getPlan().getCode()).isEqualTo("PRO");
        // Base: 100.00 + Processing (2%): 2.00 + AI (30%): 30.00 = 132.00 GHS (13200 minor units)
        assertThat(intent.getExpectedAmount()).isEqualByComparingTo(new BigDecimal("132.00"));
        assertThat(intent.getBaseAmount()).isEqualByComparingTo(new BigDecimal("100.00"));
        assertThat(intent.getProcessingFeeAmount()).isEqualByComparingTo(new BigDecimal("2.00"));
        assertThat(intent.getAiGenerationFeeAmount()).isEqualByComparingTo(new BigDecimal("30.00"));
        assertThat(intent.getTotalAmount()).isEqualByComparingTo(new BigDecimal("132.00"));
        assertThat(moneyMinorUnitConverter.toMinorUnits(intent.getExpectedAmount(), intent.getCurrency())).isEqualTo(13200L);
    }

    @Test
    void yearlyCheckoutRejectedWhenYearlyPriceNotConfigured() throws Exception {
        InitializePaymentRequest request = new InitializePaymentRequest("STUDENT", BillingInterval.YEARLY);

        mockMvc.perform(post("/api/v1/workspaces/{workspaceId}/billing/initialize", workspace.getId())
                        .header("Authorization", userToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.message", containsString("Yearly billing is not configured for plan 'STUDENT'")));
    }

    @Test
    void userCanInitializeProUpgradeWithServerAuthoritativePricing() throws Exception {
        InitializePaymentRequest request = new InitializePaymentRequest("PRO", BillingInterval.MONTHLY);

        mockMvc.perform(post("/api/v1/workspaces/{workspaceId}/billing/initialize", workspace.getId())
                        .header("Authorization", userToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.authorizationUrl", containsString("checkout.paystack.com")))
                .andExpect(jsonPath("$.reference", notNullValue()));

        // Check intent and attempt created in database
        List<BillingPaymentIntent> intents = intentRepository
                .findAllByWorkspaceIdOrderByCreatedAtDesc(workspace.getId(), Pageable.unpaged())
                .getContent();
        assertThat(intents).isNotEmpty();

        BillingPaymentIntent intent = intents.get(0);
        assertThat(intent.getPlan().getCode()).isEqualTo("PRO");
        assertThat(intent.getExpectedAmount()).isEqualByComparingTo(new BigDecimal("132.00"));
        // After initialization begins, status transitions to PAYMENT_PENDING
        assertThat(intent.getStatus()).isIn(PaymentIntentStatus.OPEN, PaymentIntentStatus.PAYMENT_PENDING);

        List<PaymentAttempt> attempts = attemptRepository
                .findAllByPaymentIntentIdOrderByAttemptNumberAsc(intent.getId());
        assertThat(attempts).hasSize(1);
        PaymentAttempt attempt1 = attempts.get(0);
        assertThat(attempt1.getAttemptNumber()).isEqualTo(1);
        assertThat(attempt1.getStatus()).isEqualTo(PaymentAttemptStatus.PENDING);
    }

    @Test
    void retryPaymentCreatesAttemptNumberTwo() throws Exception {
        // 1. Initial attempt
        InitializePaymentRequest request = new InitializePaymentRequest("PRO", BillingInterval.MONTHLY);
        mockMvc.perform(post("/api/v1/workspaces/{workspaceId}/billing/initialize", workspace.getId())
                        .header("Authorization", userToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());

        BillingPaymentIntent intent = intentRepository
                .findAllByWorkspaceIdOrderByCreatedAtDesc(workspace.getId(), Pageable.unpaged())
                .getContent()
                .get(0);

        // Simulate attempt 1 failure so that the intent is retryable
        PaymentAttempt attempt1 = attemptRepository
                .findAllByPaymentIntentIdOrderByAttemptNumberAsc(intent.getId())
                .get(0);
        attempt1.setStatus(PaymentAttemptStatus.FAILED);
        attempt1.setCompletedAt(java.time.OffsetDateTime.now().minusMinutes(1));
        attemptRepository.saveAndFlush(attempt1);

        // 2. Retry
        mockMvc.perform(post("/api/v1/billing/payment-intents/{intentId}/retry", intent.getId())
                        .header("Authorization", userToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.attemptNumber", is(2)))
                .andExpect(jsonPath("$.authorizationUrl", containsString("checkout.paystack.com")));

        List<PaymentAttempt> attempts = attemptRepository
                .findAllByPaymentIntentIdOrderByAttemptNumberAsc(intent.getId());
        assertThat(attempts).hasSize(2);
        assertThat(attempts.get(1).getAttemptNumber()).isEqualTo(2);
    }

    @Test
    void verificationOfPaymentAttemptUpgradesSubscriptionToPro() throws Exception {
        // 1. Initialize intent
        InitializePaymentRequest request = new InitializePaymentRequest("PRO", BillingInterval.MONTHLY);
        mockMvc.perform(post("/api/v1/workspaces/{workspaceId}/billing/initialize", workspace.getId())
                        .header("Authorization", userToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());

        BillingPaymentIntent intent = intentRepository
                .findAllByWorkspaceIdOrderByCreatedAtDesc(workspace.getId(), Pageable.unpaged())
                .getContent()
                .get(0);
        PaymentAttempt attempt = attemptRepository
                .findAllByPaymentIntentIdOrderByAttemptNumberAsc(intent.getId())
                .get(0);

        // 2. Mock Paystack verification response
        Mockito.when(paymentProvider.verify(anyString())).thenAnswer(inv -> {
            String ref = inv.getArgument(0);
            PaymentAttempt a = attemptRepository.findByInternalReference(ref).orElse(attempt);
            BillingPaymentIntent pi = a.getPaymentIntent();
            com.fasterxml.jackson.databind.node.ObjectNode meta =
                    objectMapper.createObjectNode()
                            .put("internalPaymentIntentId", pi.getId().toString())
                            .put("internalPaymentAttemptId", a.getId().toString())
                            .put("workspaceId", pi.getWorkspace().getId().toString())
                            .put("planCode", pi.getPlan().getCode())
                            .put("billingInterval", pi.getBillingInterval().name());
            return new PaystackVerificationResponse(
                    true,
                    "Verification successful",
                    new PaystackVerificationData("success", ref,
                            moneyMinorUnitConverter.toMinorUnits(pi.getExpectedAmount(), pi.getCurrency()),
                            pi.getCurrency(), meta)
            );
        });

        // 3. Verify attempt
        mockMvc.perform(post("/api/v1/billing/payment-attempts/{attemptId}/verify", attempt.getId())
                        .header("Authorization", userToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status", is("SUCCESS")))
                .andExpect(jsonPath("$.planCode", is("PRO")));

        // 4. Check workspace subscription is now PRO
        WorkspaceSubscription activeSub = subscriptionRepository
                .findActiveSubscription(workspace.getId())
                .orElseThrow();
        assertThat(activeSub.getPlan().getCode()).isEqualTo("PRO");
        assertThat(activeSub.getCurrentPeriodEnd()).isNotNull();
    }

    @Test
    void verificationFailsWhenPaystackReturnsMismatchedAmount() throws Exception {
        // 1. Initialize intent for PRO (100.00 GHS -> 10000 minor units)
        InitializePaymentRequest request = new InitializePaymentRequest("PRO", BillingInterval.MONTHLY);
        mockMvc.perform(post("/api/v1/workspaces/{workspaceId}/billing/initialize", workspace.getId())
                        .header("Authorization", userToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());

        BillingPaymentIntent intent = intentRepository
                .findAllByWorkspaceIdOrderByCreatedAtDesc(workspace.getId(), Pageable.unpaged())
                .getContent()
                .get(0);
        PaymentAttempt attempt = attemptRepository
                .findAllByPaymentIntentIdOrderByAttemptNumberAsc(intent.getId())
                .get(0);

        // 2. Mock Paystack verification response returning only 1000 minor units (10.00 GHS)
        Mockito.when(paymentProvider.verify(anyString())).thenAnswer(inv -> {
            String ref = inv.getArgument(0);
            PaymentAttempt a = attemptRepository.findByInternalReference(ref).orElse(attempt);
            BillingPaymentIntent pi = a.getPaymentIntent();
            com.fasterxml.jackson.databind.node.ObjectNode meta =
                    objectMapper.createObjectNode()
                            .put("internalPaymentIntentId", pi.getId().toString())
                            .put("internalPaymentAttemptId", a.getId().toString())
                            .put("workspaceId", pi.getWorkspace().getId().toString())
                            .put("planCode", pi.getPlan().getCode())
                            .put("billingInterval", pi.getBillingInterval().name());
            return new PaystackVerificationResponse(
                    true,
                    "Verification successful",
                    new PaystackVerificationData("success", ref,
                            1000L, // Wrong amount! (10.00 GHS instead of 100.00 GHS)
                            pi.getCurrency(), meta)
            );
        });

        // 3. Verify attempt
        mockMvc.perform(post("/api/v1/billing/payment-attempts/{attemptId}/verify", attempt.getId())
                        .header("Authorization", userToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status", is("VERIFICATION_FAILED")));

        // 4. Verify subscription is NOT upgraded to PRO, remains FREE
        WorkspaceSubscription activeSub = subscriptionRepository
                .findActiveSubscription(workspace.getId())
                .orElseThrow();
        assertThat(activeSub.getPlan().getCode()).isEqualTo("FREE");
    }

    @Test
    void earlyRenewalExtendsExistingPeriodEndWithoutDuplicateActiveSubscription() throws Exception {
        // 1. Set existing active PRO subscription ending in 10 days
        WorkspaceSubscription existingSub = subscriptionRepository
                .findActiveSubscription(workspace.getId())
                .orElseThrow();
        existingSub.setPlan(proPlan);
        existingSub.setBillingInterval(BillingInterval.MONTHLY);
        java.time.OffsetDateTime now = java.time.OffsetDateTime.now();
        java.time.OffsetDateTime initialEnd = now.plusDays(10);
        existingSub.setCurrentPeriodStart(now.minusDays(20));
        existingSub.setCurrentPeriodEnd(initialEnd);
        subscriptionRepository.saveAndFlush(existingSub);

        // 2. Initialize renewal payment
        InitializePaymentRequest request = new InitializePaymentRequest("PRO", BillingInterval.MONTHLY);
        mockMvc.perform(post("/api/v1/workspaces/{workspaceId}/billing/initialize", workspace.getId())
                        .header("Authorization", userToken)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk());

        BillingPaymentIntent intent = intentRepository
                .findAllByWorkspaceIdOrderByCreatedAtDesc(workspace.getId(), Pageable.unpaged())
                .getContent()
                .get(0);
        PaymentAttempt attempt = attemptRepository
                .findAllByPaymentIntentIdOrderByAttemptNumberAsc(intent.getId())
                .get(0);

        // 3. Mock Paystack verification response with correct amount
        Mockito.when(paymentProvider.verify(anyString())).thenAnswer(inv -> {
            String ref = inv.getArgument(0);
            PaymentAttempt a = attemptRepository.findByInternalReference(ref).orElse(attempt);
            BillingPaymentIntent pi = a.getPaymentIntent();
            com.fasterxml.jackson.databind.node.ObjectNode meta =
                    objectMapper.createObjectNode()
                            .put("internalPaymentIntentId", pi.getId().toString())
                            .put("internalPaymentAttemptId", a.getId().toString())
                            .put("workspaceId", pi.getWorkspace().getId().toString())
                            .put("planCode", pi.getPlan().getCode())
                            .put("billingInterval", pi.getBillingInterval().name());
            return new PaystackVerificationResponse(
                    true,
                    "Verification successful",
                    new PaystackVerificationData("success", ref,
                            moneyMinorUnitConverter.toMinorUnits(pi.getExpectedAmount(), pi.getCurrency()),
                            pi.getCurrency(), meta)
            );
        });

        // 4. Verify attempt
        mockMvc.perform(post("/api/v1/billing/payment-attempts/{attemptId}/verify", attempt.getId())
                        .header("Authorization", userToken))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.status", is("SUCCESS")));

        // 5. Check subscription: still active PRO, period end extended from initialEnd (+1 month)
        WorkspaceSubscription updatedSub = subscriptionRepository
                .findActiveSubscription(workspace.getId())
                .orElseThrow();
        assertThat(updatedSub.getPlan().getCode()).isEqualTo("PRO");
        // Verify currentPeriodEnd was extended from initialEnd (+1 month) rather than from now
        assertThat(updatedSub.getCurrentPeriodEnd()).isEqualTo(initialEnd.plusMonths(1));
    }

    @Test
    void paystackCallbackRedirectsToPaymentResult() throws Exception {
        // The Paystack callback endpoint is public (no auth required)
        mockMvc.perform(get("/api/v1/billing/paystack/callback")
                        .param("reference", "PA_NON_EXISTENT_REF"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/app/billing/payment-result?reference=PA_NON_EXISTENT_REF"));
    }
}
