package com.researchassistant.usage;

public enum UsageMetricType {
    AI_GENERATION_REQUEST,
    AI_INPUT_TOKEN,
    AI_OUTPUT_TOKEN,
    AI_TOTAL_TOKEN,
    EMBEDDING_REQUEST,
    EMBEDDING_TOKEN,
    EMBEDDED_CHUNK,
    STORAGE_BYTES,
    PROJECT_COUNT,
    ACTIVE_PROJECT_COUNT,
    DOCUMENT_COUNT,
    COLLABORATOR_COUNT,
    REPORT_EXPORT,
    SIMILARITY_CHECK,
    OTHER
}
