package com.researchassistant.collaboration.entity;

public enum CollaborationArtifactType {
    RESEARCH_PROBLEM,
    OBJECTIVE,
    RESEARCH_QUESTION,
    LITERATURE_REVIEW,
    LITERATURE_REVIEW_SECTION,
    CONCEPTUAL_FRAMEWORK,
    THEORETICAL_FRAMEWORK,
    METHODOLOGY,
    QUESTIONNAIRE,
    INTERVIEW_GUIDE,
    FOCUS_GROUP_GUIDE,
    OBSERVATION_CHECKLIST,
    DATASET,
    ANALYSIS_PLAN,
    ANALYSIS_RESULT,
    FINDING,
    DISCUSSION,
    CONCLUSION,
    RECOMMENDATION,
    REPORT,
    REPORT_CHAPTER,
    REPORT_SECTION,
    DOCUMENT,
    OTHER
}
