package com.researchassistant.ai.orchestration;

public enum AiTaskType {
    GROUNDED_QA,
    RESEARCH_PROBLEM_DRAFT,
    OBJECTIVE_DRAFT,
    RESEARCH_QUESTION_DRAFT,
    HYPOTHESIS_DRAFT,
    LITERATURE_MATRIX_EXTRACTION,
    LITERATURE_REVIEW_DRAFT,
    CONCEPTUAL_FRAMEWORK_DRAFT,
    THEORETICAL_FRAMEWORK_DRAFT,
    METHODOLOGY_DRAFT,
    DATA_COLLECTION_METHOD_DRAFT,
    QUESTIONNAIRE_DRAFT,
    INTERVIEW_GUIDE_DRAFT,
    FOCUS_GROUP_GUIDE_DRAFT,
    OBSERVATION_CHECKLIST_DRAFT,
    QUALITATIVE_CODE_SUGGESTION,
    QUALITATIVE_THEME_SUGGESTION,
    FINDING_DRAFT,
    DISCUSSION_DRAFT,
    CONCLUSION_DRAFT,
    RECOMMENDATION_DRAFT,
    REPORT_SECTION_DRAFT,
    ACADEMIC_WRITING_REVIEW
}
