package com.researchassistant.audit;

public enum AuditEventType {
    SUBSCRIPTION_CHANGED,
    SUBSCRIPTION_CANCELLED,
    PAYMENT_INITIALIZED,
    PAYMENT_RETRY_INITIALIZED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_ATTEMPT_FAILED,
    PAYMENT_ATTEMPT_SUCCEEDED,
    PAYMENT_DUPLICATE_SUCCESS_DETECTED,
    COMPLIMENTARY_ACCESS_GRANTED,
    COMPLIMENTARY_ACCESS_REVOKED,
    ADMIN_USER_SUSPENDED,
    ADMIN_USER_REACTIVATED,
    ADMIN_PLAN_CHANGED,
    NOTIFICATION_SENT
}
