package com.researchassistant.subscription;

public enum PlanFeature {
    AI_GENERATION,
    AI_EMBEDDINGS,
    AI_TOKENS,
    SEMANTIC_SEARCH,
    PROJECT_CREATION,
    COLLABORATION,
    COLLABORATORS_PER_PROJECT,
    DOCUMENT_UPLOAD,
    DOCUMENT_COUNT,
    REPORT_EXPORT,
    REPORT_EXPORT_DOCX,
    REPORT_EXPORT_PDF,
    ADVANCED_STATISTICS,
    QUALITATIVE_AI,
    SIMILARITY_CHECK,
    STORAGE,
    API_ACCESS,
    PRIORITY_SUPPORT,
    OTHER
}
