package com.researchassistant.analysis.entity;

public enum ReportSectionType {
    TITLE_PAGE,
    ABSTRACT,
    BACKGROUND,
    PROBLEM_STATEMENT,
    OBJECTIVES,
    RESEARCH_QUESTIONS,
    HYPOTHESES,
    SIGNIFICANCE,
    SCOPE,
    LITERATURE_REVIEW,
    CONCEPTUAL_REVIEW,
    THEORETICAL_REVIEW,
    EMPIRICAL_REVIEW,
    RESEARCH_GAP,
    CONCEPTUAL_FRAMEWORK,
    METHODOLOGY,
    RESULTS,
    FINDINGS,
    DISCUSSION,
    CONCLUSIONS,
    RECOMMENDATIONS,
    REFERENCES,
    APPENDIX,
    CUSTOM
}
