package com.researchassistant.integrity.entity;
public enum WritingIssueType { GRAMMAR, SPELLING, CLARITY, CONCISION, ACADEMIC_TONE, AMBIGUITY, REDUNDANCY, PARAGRAPH_STRUCTURE, TRANSITION, TENSE_CONSISTENCY, PERSON_USAGE, UNSUPPORTED_CLAIM, MISSING_CITATION, CITATION_MISMATCH, OVERSTATEMENT, CAUSAL_LANGUAGE, STATISTICAL_REPORTING, OTHER }
