package com.researchassistant.reference.entity;

public enum ReferenceType {
    JOURNAL_ARTICLE, BOOK, BOOK_CHAPTER, CONFERENCE_PAPER, THESIS, DISSERTATION, REPORT, WEB_PAGE,
    DATASET, GOVERNMENT_DOCUMENT, STANDARD, NEWSPAPER_ARTICLE, MAGAZINE_ARTICLE, WORKING_PAPER,
    PREPRINT, SOFTWARE, OTHER
}
