package com.researchassistant.methodology.entity;

public enum ResearchDesignType {
    UNSPECIFIED,
    DESCRIPTIVE,
    CROSS_SECTIONAL,
    CASE_STUDY,
    EXPERIMENTAL,
    QUASI_EXPERIMENTAL,
    CORRELATIONAL,
    EXPLORATORY,
    EXPLANATORY,
    PHENOMENOLOGICAL,
    ETHNOGRAPHIC,
    GROUNDED_THEORY,
    NARRATIVE,
    ACTION_RESEARCH,
    COHORT,
    CASE_CONTROL,
    MIXED_METHODS_CONVERGENT,
    MIXED_METHODS_EXPLANATORY_SEQUENTIAL,
    MIXED_METHODS_EXPLORATORY_SEQUENTIAL,
    OTHER
}
