package com.researchassistant.notification;

public enum NotificationType {
    PROJECT_INVITATION,
    TASK_ASSIGNED,
    TASK_DUE_SOON,
    COMMENT_MENTION,
    REVIEW_REQUESTED,
    CHANGES_REQUESTED,
    APPROVAL_GRANTED,
    AI_QUOTA_WARNING,
    AI_QUOTA_EXCEEDED,
    STORAGE_QUOTA_WARNING,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_EXPIRED,
    PAYMENT_RETRY_AVAILABLE,
    COMPLIMENTARY_ACCESS_GRANTED,
    COMPLIMENTARY_ACCESS_EXPIRING,
    COMPLIMENTARY_ACCESS_REVOKED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_CANCELLED,
    BACKUP_FAILURE,
    REPORT_EXPORT_COMPLETED
}
